// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueaXX59hl-kB6P3zhC9GZdL5VlOE3xD0',
    appId: '1:584380309787:web:6d22c3c0fb7e4d61c4b3be',
    messagingSenderId: '584380309787',
    projectId: 'parking-iteso-proyecto',
    authDomain: 'parking-iteso-proyecto.firebaseapp.com',
    storageBucket: 'parking-iteso-proyecto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sqye9ajOhW9_u-2W0OpHjijzx9I1CnE',
    appId: '1:584380309787:android:d8ed77cb54da18c6c4b3be',
    messagingSenderId: '584380309787',
    projectId: 'parking-iteso-proyecto',
    storageBucket: 'parking-iteso-proyecto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFtNVn_LlmRZkD3-q7YQ3RaKVFW2GSp8',
    appId: '1:584380309787:ios:781f179cbc97b6aec4b3be',
    messagingSenderId: '584380309787',
    projectId: 'parking-iteso-proyecto',
    storageBucket: 'parking-iteso-proyecto.appspot.com',
    androidClientId: '584380309787-8gmgioqhdl59gtsmhphepmrddepefko7.apps.googleusercontent.com',
    iosClientId: '584380309787-6ghc9l7gfno9dltijfmn6p9dn3f1mi0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFtNVn_LlmRZkD3-q7YQ3RaKVFW2GSp8',
    appId: '1:584380309787:ios:c207826606878b3bc4b3be',
    messagingSenderId: '584380309787',
    projectId: 'parking-iteso-proyecto',
    storageBucket: 'parking-iteso-proyecto.appspot.com',
    androidClientId: '584380309787-8gmgioqhdl59gtsmhphepmrddepefko7.apps.googleusercontent.com',
    iosClientId: '584380309787-tmpseqauhinm79ovk98gqsnatlpjt0ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
