name: project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  google_maps_flutter: ^2.5.0
  flutter_config: ^2.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.5
  after_layout: ^1.2.0
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
